### ISSUE TITLE
Zapier integration - 443 Curl issue

### ISSUE THREAD

**Issue by jrameriz** [RensTillmann/super-forms#22]
Today I created and tried to make a new zap added both 1.1.0 and 1.0.0 version of Superforms and it gave me this error: cURL error 35: Unknown SSL protocol error in connection to hooks.zapier.com:443

See screenshot. 
![Screen Shot 2020-03-25 at 7 30 07 AM](https://user-images.githubusercontent.com/4984630/77547926-128ce100-6e6b-11ea-9a82-2140bb3c77c0.png)
![Screen Shot 2020-03-25 at 7 29 42 AM](https://user-images.githubusercontent.com/4984630/77547949-17519500-6e6b-11ea-9e3e-a3b66b7c5f8e.png)
![Screen Shot 2020-03-25 at 7 24 54 AM](https://user-images.githubusercontent.com/4984630/77547974-20426680-6e6b-11ea-80fa-d5506c6a2df5.png)

**Comment by RensTillmann** [comment]
Hi, this error isn't generated by Super Forms, it can't be fixed by Super Forms either. 

This error is mostly generated when your site is running on an outdated server :)

Try switching off support for TLS 1.0.
Update curl and OpenSSL (for security reasons too)
If you are not sure how to do this or run into issues, contact your host.

**Comment by jrameriz** [comment]
our other forms did not generate this issue.

**Comment by RensTillmann** [comment]
They are on a different server perhaps? This is really related to server, not super forms, can't help you with this sorry. You will have to contact host.

**Comment by jrameriz** [comment]
Thank you for your fast response. I really appreciate it!
