### ISSUE TITLE
Failed To Process Data

### ISSUE THREAD

**Issue by Billions88** [RensTillmann/super-forms#40]
Any reason as to why this is happening? It seems to happen most when I use the upload attachment option with photos. I tired removing the upload limit, but when I go back to the form settings, it defaults to 5MB. I changed the upload limit to 100MB, as well as the file size limit. The form processing box pops up for about 30 seconds and another message that says "Failed to process data". The processing data box is still visible with the rotating swirl. I don't have any active add-ons such as the PDF conversion, etc.

Hopefully we can determine whats happening here.

**Comment by Billions88** [comment]
Also, its not my allowed extensions. I have it set as jpg|jpeg|png|gif|pdf|doc|rtf|docx|otd|txt|

**Comment by RensTillmann** [comment]
Hi, I think the problem is more with the server limitations. Please read this article here on how to possible determine and solve this:
https://webrehab.zendesk.com/hc/en-gb/articles/360016903597-Why-do-I-get-an-error-message-when-uploading-a-file-

You probably will also not be able to upload that exact same file through "Media Library" within WordPress because it's to large to process by the server.

**Comment by Billions88** [comment]
Thank you for your quick response. I will look into that. I previously added the following code to my .php file. Does this suffice, or should I go with the code from the link you sent me. 

define( 'ALLOW_UNFILTERED_UPLOADS',  true ):

**Comment by RensTillmann** [comment]
**define( 'ALLOW_UNFILTERED_UPLOADS', true );** is not something you'd want to use unless you what no restriction in what types. However adding this won't change the extensions that you allow for your file upload element in super forms. So adding this won't affect much in that sense. Nor is it related to your issue. Your issue seems only to be the "size" that your server is able to handle.

You can confirm this by looking into the server logs to be completely sure that this is the reason.

**Comment by Billions88** [comment]
I contacted Hostgator and they have maximized the server size for file uploads in php. I have no clue as to what else could be stopping the form from not processing. As I mentioned, the form goes through perfectly without any photo attachments. I attached 3 photos that were 26KB a piece and the form submitted, but when I upload any photos over 26KB the form doesn't send.

**Comment by Billions88** [comment]
I spoke to another rep and they have changed the upload memory size in MultiPHP ini 

The email is going through with the multiple photos attached, but the form still says "Processing form data..." with the spinning swirl. It's not recognizing that the form is being sent to switch to the thank you message.

**Comment by RensTillmann** [comment]
If it's stuck at processing form data, it means you have some sort of Javascript error (most likely) for whatever reason may be. I suggest you to submit a ticket for that here (http://f4d.nl/super-forms/support), and provide details such as:
- page to URL
- temp admin login (if possible)
